stages:
  - build
  - test
  - deploy

dev:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  when: always

stage1:
  stage: test
  script:
    - echo "This job tests something"
  when: manual 
  needs:
    - job: dev

stage2:
  stage: test
  script:
    - echo "This job tests something but takes more time than stage1"
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - sleep 20
  when: manual 
  needs:
    - job: dev

deploy-prod:
  stage: deploy
  script: 
    - echo "This job deploys prod"
  environment: production
  when: manual 
  needs:
    - job: stage1
    - job: stage2


